# Generated by Django 3.2.6 on 2021-12-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passengers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passengers',
        ),
    ]
